// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2r59wMx8rz1Vkz2YIEwlF3Jsg3TTGXUE',
    appId: '1:391610566299:android:62340fff58273448fc283e',
    messagingSenderId: '391610566299',
    projectId: 'bus-system-management',
    databaseURL: 'https://bus-system-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-system-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUq1B35Ymn3GIfMtwWytnzoLJhKcunDQ',
    appId: '1:391610566299:ios:9a91d23c5d1881b7fc283e',
    messagingSenderId: '391610566299',
    projectId: 'bus-system-management',
    databaseURL: 'https://bus-system-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-system-management.appspot.com',
    androidClientId: '391610566299-v2iukoaa3kav3mm8nqb0fouhfsufjk2k.apps.googleusercontent.com',
    iosClientId: '391610566299-5kcr5lf88vciger1arv7m229ju2vl5m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.busSystemManagement',
  );
}
